caseconsulting/expense-app-api

- chiron/package-lock.json
- chiron/package.json
- chronos/package-lock.json
- chronos/package.json
- package-lock.json
- package.json
- portal-data-sync/package-lock.json
- portal-data-sync/package.json
- thanos/package-lock.json
- thanos/package.json
Ticket Link: [https://consultwithcase.atlassian.net/jira/software/c/projects/POR/boards/7?selectedIssue=POR-2612]
update package version number
> POR-2612 update package version number

- routes/googleMapsRoutes.js
Ticket Link: [POR-2628](https://consultwithcase.atlassian.net/jira/software/c/projects/POR/boards/7?label=Interns&selectedIssue=POR-2628)
Fixed zip code bug
[POR-2628]: https://consultwithcase.atlassian.net/browse/POR-2628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Madelineburns master por 2628 autofilled google api for pob

- routes/attachmentRoutes.js
Ticket Link [POR-1042](https://consultwithcase.atlassian.net/browse/POR-1042)
Deletes all attachments from the expense when deleted. Added function to retrieve all objects from a folder in a S3 bucket
How to test: Added an expense with an attachment, then edit and change the attachment, then delete the expense
- Check services.log for deletion log
-  example: 'Listing 2 keys from ...' and 'Successfully deleted 2 attachments for expense ...'
[POR-1042]: https://consultwithcase.atlassian.net/browse/POR-1042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> POR 1042 - delete all expense attachments

- package.json
Ticket Link [POR-2760](https://consultwithcase.atlassian.net/browse/POR-2760)
Updated version to 4.6.0
[POR-2760]: https://consultwithcase.atlassian.net/browse/POR-2760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> POR 2760 - 4.6.0 version

- routes/basecampRoutes.js
- routes/utilityRoutes.js
- spec/routes/basecampRoutes.spec.js
- spec/routes/utilityRoutes.spec.js
Ticket link: [POR 1760](https://consultwithcase.atlassian.net/browse/POR-1760)
Fetch HQ message board contents from basecamp api.
> POR 1760 - hq announcements in activity feed

- package-lock.json
- routes/tagRoutes.js
Ticket link: https://consultwithcase.atlassian.net/jira/software/c/projects/POR/boards/7?selectedIssue=POR-2786
> POR-2786: 500 Error when updating employee tags

- routes/expenseTypeRoutes.js
Ticket Link[POR-2803](https://consultwithcase.atlassian.net/browse/POR-2803)
Fixed updating expenseTypes when no body exists
> POR 2803 - expense-type-form-custom-employee-access-bug 

- js/Scripts/attachmentScripts.js
- js/Scripts/deleteUnusedExpenseAttachments.js
Ticket Link [POR-2759](https://consultwithcase.atlassian.net/browse/POR-2759)
Attachment script which deletes all unused expense attachments from S3 that are not referenced in DynamoDB
How to test:
run `node ./js/Scripts/attachmentScripts.js dev`
- add expense with attachments
- edit expense attachment
- run script
- scan receipt for expense
- run script
[POR-2759]: https://consultwithcase.atlassian.net/browse/POR-2759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> POR 2759 - delete unused attachments script

- models/employee.js
Ticket link: https://consultwithcase.atlassian.net/jira/software/c/projects/POR/boards/7?selectedIssue=POR-2824
> POR-2824: add legacy job codes attribute to employee model

- js/Scripts/attachmentScripts.js
- js/databaseModify.js
- models/employee-sensitive.js
- models/employee.js
- routes/crudRoutes.js
- routes/employeeRoutes.js
- spec/js/databaseModify.spec.js
- spec/routes/employeeRoutes.spec.js
Ticket Link [POR-2671](https://consultwithcase.atlassian.net/browse/POR-2671)
Added route for crud and employee routes for updating multiple attributes in one patch
Added databaseModify method which does a transaction on multiple tables
Added crudRoutes route and method to updateMultiple attributes, which invokes transactions
Added employeeRoutes method to validate updating multiple attributes and denotes which tables to update.
How to test:
- Postman
[POR-2671]: https://consultwithcase.atlassian.net/browse/POR-2671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> POR 2671 - create backend route

- js/databaseModify.js
- spec/js/databaseModify.spec.js
Ticket Link [POR-2888](https://consultwithcase.atlassian.net/browse/POR-2888)
Fixed bug when passing no attributes to update/empty object/no body
How to test:
- Postman
- - Run update attributes with empty body or no body
[POR-2888]: https://consultwithcase.atlassian.net/browse/POR-2888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> POR 2888 - fixed bug when updating no attributes

- models/employee.js
Ticket link: [POR 2825](https://consultwithcase.atlassian.net/browse/POR-2825)
Added personalEmailHidden as an allowed field in the employee database table
> POR 2825: add personalEmailHidden field to employee

- js/databaseModify.js
- models/employee-sensitive.js
- models/employee.js
- routes/crudRoutes.js
- routes/employeeRoutes.js
- spec/js/databaseModify.spec.js
- spec/routes/employeeRoutes.spec.js
Merge beta profile page to master
> POR 2576: profile page redesign

- chronos/chronos.js
- models/budget.js
- routes/crudRoutes.js
- routes/employeeRoutes.js
- routes/expenseRoutes.js
- routes/expenseTypeRoutes.js
- routes/tagRoutes.js
- spec/routes/employeeRoutes.spec.js
- spec/routes/expenseTypeRoutes.spec.js
> Deploy to test

- models/employee.js
- routes/employeeRoutes.js
https://consultwithcase.atlassian.net/browse/POR-3073
- format the email as lowercase
- validate the email is lowercase
> POR-3073 Save employee emails as lowercase

- models/employee.js
- portal-data-sync/package-lock.json
- routes/employeeRoutes.js
https://consultwithcase.atlassian.net/jira/software/c/projects/POR/boards/12?selectedIssue=POR-3099
> POR-3099: Timesheet Reminder Table

- routes/timesheetsRoutes.js
https://consultwithcase.atlassian.net/browse/POR-3121
> POR-3121 1860 Leaderboard

- routes/timesheetsRoutes.js
Reverts caseconsulting/expense-app-api#182
> Revert "POR-3121 1860 Leaderboard"

- CloudFormation.yaml
- chiron/package.json
- chronos/package-lock.json
- chronos/package.json
- crons/leaderboard/leaderboard.js
- crons/leaderboard/package-lock.json
- crons/leaderboard/package.json
- js/databaseModify.js
- js/dateUtils.js
- js/utils.js
- js/utils/timesheet.js
- layers/shared/nodejs/package-lock.json
- layers/shared/nodejs/package.json
- models/timesheet.js
- package-lock.json
- package.json
- portal-data-sync/package-lock.json
- portal-data-sync/package.json
- routes/timesheetsRoutes.js
- thanos/package-lock.json
- thanos/package.json
https://consultwithcase.atlassian.net/browse/POR-3159
> POR-3159 Warehouse Leaderboard Data

- CloudFormation.yaml
* POR-3147: update cors policy to allow for image retreival
* POR-3147: fix bugs
> logburn-master-POR-3147 (#192)

- models/employee.js
Ticket Link: [POR 3158](https://consultwithcase.atlassian.net/browse/POR-3158)
Added unanet person key to portal.
> POR 3158 - Adding unanet person key

- models/audits/notification.js
- routes/auditRoutesV2.js
Ticket Link: [POR 3190](https://consultwithcase.atlassian.net/browse/POR-3190)
Added backend route to insert rows, uses dummy data (my data) to insert as of right now.
> POR 3190 - created backend route to insert row

- app.js
- routes/auditRoutesV2.js
Ticket Link: [POR 3191](https://consultwithcase.atlassian.net/browse/POR-3191)
Created backend route to query the audits in the database (only for notifications right now) based on time range.
> POR 3191 - Creating backend route to query the audits (notifications only)

- routes/auditRoutesV2.js
<https://consultwithcase.atlassian.net/browse/POR-3207>
Created a helper method that handles it, should be used in place of creating and sending an ExecuteStatementCommand
> POR-3207 handle database resuming exception when querying audits

- app.js
- models/audits/audits.js
- models/audits/notification.js
- routes/auditRoutesV2.js
<https://consultwithcase.atlassian.net/browse/POR-3208>
- Added an AuditRoutesV2 class to be consistent with other files in the routes folder
- Use jwt middleware to authenticate requests
> POR-3208 make auditRoutesV2.js consistent with other route files

- CloudFormation.yaml
- js/Scripts/audits/createAuditsTables.js
- js/Scripts/audits/create_audits_tables.sql
- js/aurora/auroraClient.js
- layers/shared/nodejs/package-lock.json
- layers/shared/nodejs/package.json
- models/audits/audits.js
- models/audits/notification.js
- routes/auditRoutesV2.js
- timesheet-submission-reminder/app.js
- timesheet-submission-reminder/case-helpers.js
<https://consultwithcase.atlassian.net/browse/POR-3204>
> POR-3204: audit timesheet submission reminders

- routes/timesheetsRoutes.js
https://consultwithcase.atlassian.net/browse/POR-3195
> POR-3195 Always show current user on leaderboard

- routes/timesheetsRoutes.js
<https://consultwithcase.atlassian.net/browse/POR-3221>
- validate csv files in the backend before storing
- extract info from csv file and upload as json
> POR-3221: use updated csv format and store as json

- js/utils/timesheet.js
- routes/timesheetsRoutes.js
<https://consultwithcase.atlassian.net/browse/POR-3228>
> POR-3288: handle error when s3 object does not exist

- CloudFormation.yaml
- crons/leaderboard/leaderboard.js
https://consultwithcase.atlassian.net/browse/POR-3218
> POR-3218 Fix leaderboard cron

- portal-data-sync/getters.js
Ticket Link: [POR 3242](https://consultwithcase.atlassian.net/browse/POR-3242)
Fixed bamboo lambda sync to prevent Dylan and Madeline and any potential inactive and terminated employees from reappearing in Bamboo.
> POR 3242 - Fixed bamboo sync 

- js/utils/timesheet.js
- timesheet-submission-reminder/case-helpers.js
Ticket Link: [POR 3237](https://consultwithcase.atlassian.net/browse/POR-3237)
Switch the text reminder to use the existing lambda function for time instead of the API directly
> POR 3237 - text reminders using lambda function instead of api directly

- timesheet-submission-reminder/app.js
- timesheet-submission-reminder/case-helpers.js
https://consultwithcase.atlassian.net/browse/POR-3289
> POR-3289 Fix text reminders for timesheets

- routes/expenseRoutes.js
> POR-3311 Reject expenses for past employees
